openapi: 3.1.0
info:
  version: 1.0.0
  title: WATER TRACKER APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation about Contacts App
tags:
  - name: WATER TRACKER
    description: WATER TRACKER.
  - name: Auth
    description: Operations about Authentication & Authorization.
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-ejs8.onrender.com
  #посилання на задеплоєний сайт
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/reset-pwd:
    put:
      $ref: ../swagger/paths/auth/reset-pwd/put.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /users/{id}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
  /users/{id}/avatar:
    patch:
      $ref: ../swagger/paths/users/{id}/avatar/patch.yaml

  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
